### ISSUE TITLE
External Enemies are spawned immediately upon arrival

### ISSUE THREAD

**Issue by Silhygames** [sfDesat/Aquatis#10]
Each time we arrive at Aquatis, we find it already populated with Forest Giants and Baboon Hawks as if the planet was undergoing an eclipse (it isn't). 

Aside from the minor suggestion that Forest Giants probably shouldn't spawn on the island, this does end up being a major impediment to our enjoying of the otherwise wonderful planet mod.

I'm withholding my modlist and LogOutput for now just in case this is an external issue, such as a bug with Lethal Expansion or something, so I just want to confirm.

For the record, I haven't seen universal spawn behavior issues from other planet modules installed (Infernis has a rogue spider outside, but no early spawns; Atlas Abyss has no early hostile spawns, etc.), so it leads me to believe it may be something specific to Aquatis and Orion.

**Comment by sfDesat** [comment]
Sorry for not responding. This is not a bug, however I am in the process of rebalancing the planet (Aquatis). The giants are something I want to keep, but I am changing the spawning and the enviroment to better accommodate them.

**Comment by Kroxywuff** [comment]
I don't know if 2-3 baboon hawks outside every day at 10am is something easily played around if you go here first without shovels or equipment. From my group who did 3k quota runs eclipsed things etc, it seemed unfair. Maybe with shovels/gear.

**Comment by sfDesat** [comment]
> I don't know if 2-3 baboon hawks outside every day at 10am is something easily played around if you go here first without shovels or equipment. From my group who did 3k quota runs eclipsed things etc, it seemed unfair. Maybe with shovels/gear.

If you avoid direct confrontation and become uninteresting to them, they will leave you alone most of the time. [Here is the wiki](https://lethal.miraheze.org/wiki/Baboon_Hawk).
