### ISSUE TITLE
Discord Link Expired

### ISSUE THREAD

**Issue by vinrata** [sfDesat/Aquatis#12]
hi your discord link is expired! (:

**Comment by vinrata** [comment]
I also have a question about my custom moon's fire exits not working.  it is all working great using HolographicWings Lethal SDK. My issue is with the fire exits. I copied the fire exit and changed the ID and changed the settings to overwrite fire escapes to 3. I attached some screenshots here https://imgur.com/a/rDcQgHA If someone could help me that would be awesome! (: The fire exit with ID 0 and 1 work. (main entrance and first fire escape) But the fireExits with ID 2 and 3 do not work. When attempting to enter it says "The entrance seems to be blocked"

**Comment by sfDesat** [comment]
I have not figured this issue out yet. This als happens on my custom moons. I think it is either a vanilla bug or something with the SDK. The entrances sometimes work and sometimes they don't. I read somewhere that it may be something about bookshelfs blocking the entrance? I don't know. The map look cool btw.

**Comment by sfDesat** [comment]
> hi your discord link is expired! (:

I'll look at it next update. [here is a working link](https://discord.gg/nYcQFEpXfU)

**Comment by vinrata** [comment]
I'm wondering if the bug has something to do with the dungeon generation, The SDK allows you to change the "Dungeon size 0-10. But the config file also can change the dungeon size. I wonder if these are conflicting and making the doors spawn in the wrong place.  Maybe a dungeon size of 1.68 for example, is not a whole number, therefore it could potentially generate the dungeon in an irregular way....Ive tried to load the moon and peek down into the dungeon through a transparent floor, and i feel like I see some red pixels down there that would lead me to believe there are in fact fire exits spawning, but they are inside of a wall/book shelf etc.  I need a NoClip mode or something to see it better when loaded in the game :thinking:

**Comment by sfDesat** [comment]
> I'm wondering if the bug has something to do with the dungeon generation, The SDK allows you to change the "Dungeon size 0-10. But the config file also can change the dungeon size. I wonder if these are conflicting and making the doors spawn in the wrong place. Maybe a dungeon size of 1.68 for example, is not a whole number, therefore it could potentially generate the dungeon in an irregular way....Ive tried to load the moon and peek down into the dungeon through a transparent floor, and i feel like I see some red pixels down there that would lead me to believe there are in fact fire exits spawning, but they are inside of a wall/book shelf etc. I need a NoClip mode or something to see it better when loaded in the game 🤔

Something like this is most likely the explanation, but I am pretty sure this is a vanilla bug.
