### ISSUE TITLE
Adding a short dirt cliff along the left of the island to hide from giants

### ISSUE THREAD

**Issue by TerrorPenguin** [sfDesat/Aquatis#13]
A short dirt cliff that you can crouch behind going from just past the rocks to the left of the dropship to just before the rocks next to the bridge would be great cover for giants to allow you to get near both the main entrance and fire exit, hopefully without trivialising them entirely
![Sprite-0006](https://github.com/sfDesat/Aquatis/assets/41289369/844efb1f-66d6-4f72-a1b0-81959bc958e5)

**Comment by sfDesat** [comment]
I have already done that a bit, but I heard more people talk about a slightly easier option so I will take this into consideration.

**Comment by TerrorPenguin** [comment]
Cool, looking forward to whatever changes come to the map
