### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by ImpulsiveLass** [sfDesat/Aquatis#16]
What does ExpansionAssets do? Why is it a dependency?

Also is this intentional?

https://streamable.com/dm3grv

**Comment by sfDesat** [comment]
The video you send is quicksand that is for some reason invisible. I still don't understand why (fix in the next patch). ExpansionAssets houses some assets (e.g. the rocks) that are shared between my moons. This cuts down on loading time if you have more than one of my moons installed.
