### ISSUE TITLE
[LE] Timer dissapears when exiting a facility

### ISSUE THREAD

**Issue by broilerosu** [sfDesat/Aquatis#2]
shouldnt be a mod causing it i have no mod that affects the hud 

BepInEx-BepInExPack-5.4.2100
2018-LC_API-3.0.1
Sligili-More_Emotes-1.2.2
RugbugRedfern-Skinwalkers-2.0.1
RickArg-Helmet_Cameras-2.1.5
x753-Mimics-2.2.1
tinyhoot-ShipLoot-1.0.0
sunnobunno-YippeeMod-1.2.2
OrtonLongGaming-FreddyBracken-1.0.6
FlipMods-LetMeLookDown-1.0.1
vasanex-ItemQuickSwitch-1.1.0
MetalPipeSFX-HornMoan-2.1.0
FlipMods-FasterItemDropship-1.2.0
EliteMasterEric-Coroner-1.4.2
Hexnet111-SuitSaver-1.1.2
5Bit-VoiceHUD-1.0.4
HomelessGinger-MaskedEnemyOverhaul-2.1.0
monkes_mods-JumpDelayPatch-1.0.1
Sv_Matt-HideModList-1.0.1
x753-More_Suits-1.4.1
Verity-TooManySuits-1.0.4
broiiler-broiilerskinpack-1.1.2
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.7.0
Badham_Mods-CirnoFumoScrap-1.2.1
rileyzzz-Skibidi_Toilet-1.0.1
FlipMods-SkipToMultiplayerMenu-1.0.0
Rune580-LethalCompany_InputUtils-0.4.2
quackandcheese-ToggleMute-1.3.0
AinaVT-YippeeScrap-1.0.0
Sant5050-Buy_Any_Ship_Decoration-1.0.0
AllToasters-QuickRestart-1.2.0
Silvercore-Permanent_Ladder-1.0.1
alexsio-gamba_mod-1.0.8
Ozone-BepInUtils-1.2.1
Ozone-Lockdown-1.0.3
kuba6000-LC_Masked_Fix-0.0.1
KoderTeh-Television_Controller-1.0.2
OE_Tweaks-Faster_Ship_Landing_At_Company-1.0.1
notnotnotswipez-MoreCompany-1.7.2
Evaisa-LethalThings-0.7.1
Electric131-OuijaBoard-1.5.0
CHILLAX-ChillaxSCRAPS-0.5.0
taffyko-NiceChat-1.2.2
Mercyz-PerformanceCompany-1.0.0
Stoneman-LethalProgression-1.3.2
Midge-PushCompany-1.2.0
KoderTeh-Boombox_Controller-1.1.2
tinyhoot-ShipLobby-1.0.2
HolographicWings-LethalExpansion-1.2.16
sfDesat-Aquatis-0.2.0
Gemumoddo-LethalEmotesAPI-1.0.2
Gemumoddo-BadAssCompany-1.0.2
Nips-Brutal_Company_Plus-3.4.0

Full mod list

**Comment by broilerosu** [comment]
would like to add RickArg-Helmet_Cameras did not cause an instant crash for me in solo testing

**Comment by sfDesat** [comment]
It is indeed not caused by any other mods. I will look into the issue.

**Comment by sfDesat** [comment]
A patch has been rolled out
