### ISSUE TITLE
Problem with aquatis moon

### ISSUE THREAD

**Issue by CreamBoomFoxy** [sfDesat/Aquatis#20]
**Hi, when I try to go to the aquatis moon it gives me this error:** 

`[Info   :LethalExpansion(core)] Updating fire exit count from (2 - 2) to (2 - 2)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LethalLevelLoader.LevelManager.LogDayHistory () (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_007C)
LethalLevelLoader.Patches.DungeonGeneratorGenerate_Prefix (DunGen.DungeonGenerator __instance) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_0016)
(wrapper dynamic-method) DunGen.DungeonGenerator.DMD<DunGen.DungeonGenerator::Generate>(DunGen.DungeonGenerator)
DunGen.RuntimeDungeon.Generate () (at <af9b1eec498a45aebd42601d6ab85015>:IL_002C)
LethalLevelLoader.Patches.InjectHostDungeonSizeSelection (RoundManager roundManager) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_001D)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?-1847075842(RoundManager)
LethalLevelLoader.Patches.Dungeon_GenerateNewFloor_Prefix (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_000C)
(wrapper dynamic-method) LethalLib.Modules.Dungeon.DMD<LethalLib.Modules.Dungeon::RoundManager_GenerateNewFloor>(On.RoundManager/orig_GenerateNewFloor,RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?-794682912(RoundManager)
LethalLevelLoader.Patches.InjectHostDungeonFlowSelection () (at <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_0039)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager,int,int)
RoundManager+<LoadNewLevelWait>d__115.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0076)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

_All the dependencies are installed!_

**Comment by sfDesat** [comment]
LethalLevelLoader and LethalExpansion dont work very well together. To fix this try installing LethalExpansionCore https://thunderstore.io/c/lethal-company/p/jockie/LethalExpansionCore/
