### ISSUE TITLE
[Bug] Issue with dungeons being underwater as of 2.0.0 update.

### ISSUE THREAD

**Issue by Uniteria** [sfDesat/Aquatis#22]
Hey :) Just like tittle says, there's issue with dungeons being underwater as of new patch.

**Comment by sfDesat** [comment]
Thank you for the report

**Comment by sfDesat** [comment]
This should be fixed in the latest update

**Comment by Uniteria** [comment]
> This should be fixed in the latest update

Thanks for your work! All seems fine :)
