### ISSUE TITLE
Aquatis desyncs weather in modded multiplayer.

### ISSUE THREAD

**Issue by Kayden21** [sfDesat/Aquatis#23]
Hey me and my friend just spent like 2 hours turning off each of our mods to see what is causing a weather dysync and to our surpise it is Aquatis which is one of our oldest mods downloaded. So something you updated recently seems to be messing with weather in multiplayer. We test it where literally the only mods were aquatis and the mods required to run aquatis so we know that is whats causing it. Pretty much it would cause us to have two different weathers on any moon we dropped on not just aquatis. Your other moon Orion seems to be working though.

**Comment by sfDesat** [comment]
sorry for my late reply. I think this is a bug with LethalLevelLoader and a patch will have to come via there. In the mean time there is a solution, download this https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaks/ and set in the config file, randomweather to false
