### ISSUE TITLE
Mod conflict with BetterSprayPaint by taffyko

### ISSUE THREAD

**Issue by andrzej2273** [sfDesat/Aquatis#24]
Versions 2.2.0+ have a conflict with BetterSprayPaint, There is a console spam if BSP is on.
![spray](https://github.com/sfDesat/Aquatis/assets/168291598/4298b7b8-9d8f-41cc-88e1-8c00133839b5)

**Comment by sfDesat** [comment]
I'll look into it, but BetterSprayPaint has been causing a lot of problems in general. So no garuantees

**Comment by andrzej2273** [comment]
BetterSprayPaint had an update today, the problem was fixed. I can play on newest update for Aquatis.
