### ISSUE TITLE
You can't even access the wreckage

### ISSUE THREAD

**Issue by Krampus69** [sfDesat/Aquatis#3]
Bro what's up with the wreckage not being accessible on your map ? Also why do we need to go to github just to give you feedbacks, don't you have modding discord servers ?
Anyway the level design of the map is not clear, I never found how to get in the boat there is no ladder no door and the water is too deep

**Comment by sfDesat** [comment]
There is a thread on the discord server https://discordapp.com/channels/1169792572382773318/1188025007759179857
