### ISSUE TITLE
[LE] Planet's delivery ship overwrites other planet's delivery ships.

### ISSUE THREAD

**Issue by GhostDragon122** [sfDesat/Aquatis#4]
The added delivery ship for Aquatis stays after flying to new planets. This makes it overwrite the current planet's delivery ship and cause it land somewhere inaccessible in most situations. This can be easily tested by travelling to Aquatis and then to the company, where the delivery ship will now land behind the walls.

The loaded mods are MoreCompany by notnotnotswipez, Ship Lobby by tinyhoot, Lethal Expansion, Orion and Aquatis.

[LogOutput.log](https://github.com/sfDesat/Aquatis/files/13759403/LogOutput.log)

Uninstalling and reinstalling mod didn't resolve issue

**Comment by sfDesat** [comment]
If you update Lethal Expansion to 1.3.2 it should be fixed. Thank you for reporting.
