### ISSUE TITLE
[LE] Lightning strikes player in facility

### ISSUE THREAD

**Issue by ForgotTheColon** [sfDesat/Aquatis#5]
My friend picked up a key in the facility and we were both smited by zeus.

I haven't attempted to reproduce it, so im not sure if it'll happen 100%, so just grab a brass bell and test your luck to debug it.

Mods:
BepInEx-BepInExPack-5.4.2100
OrtonLongGaming-FreddyBracken-1.0.6
zo0my-AmogusModels-1.1.0
2018-LC_API-3.1.0
Mom_Llama-Lethal_Company_Enhancer-0.1.10
tinyhoot-ShipLoot-1.0.0
FlipMods-ReservedItemSlotCore-1.6.6
FlipMods-ReservedFlashlightSlot-1.5.1
HolographicWings-LethalExpansion-1.3.6
sfDesat-Orion-1.0.0
s_nnys-RetroRobloxScrap-1.0.1
quackandcheese-MinecraftTaigaMoon-1.1.1
sfDesat-Aquatis-0.3.3
notnotnotswipez-MoreCompany-1.7.2
s_nnys-RetroRobloxCosmetics-1.0.3

[LogOutput.log](https://github.com/sfDesat/Aquatis/files/13783096/LogOutput.log)

**Comment by sfDesat** [comment]
I have seen more reports about this. It is something the developer behind Lethal Expansion (the framework I use) has to fix. He is aware of the issue and is looking into a possible fix.
