### ISSUE TITLE
Lethallib 

### ISSUE THREAD

**Issue by t1211** [sfDesat/Aquatis#6]
can there at some point be a version that doesnt use LE? it does not like my game and I really dont feel like hassling with it again after last time and i know that there have been ways to run planets through with lethallib, thats what the new ooblterra did! :D

**Comment by t1211** [comment]
also would like to mention that you linked a thread for discussing your mods on discord but didnt mention what server this is in, so when i click them it doesnt lead me anywhere 
![firefox_2023-12-29_18-52-06](https://github.com/sfDesat/Aquatis/assets/36489606/524478b7-d1a3-4a74-a5b5-864e129195ab)

**Comment by sfDesat** [comment]
There is currently no plan to use anything other than Lethal Expansion. If you are having problems with it you can request help [here](https://github.com/HolographicWings/LethalExpansion/issues). And the discord link was indeed wrong [here is a better link](https://discord.gg/nYcQFEpXfU) You need to go to mod-release and look for Orion / Aquatis.
